
name: ci-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]


jobs:
  tests:
    runs-on: ubuntu-latest
    environment: build

    strategy:
      matrix:
        node-version: [18.x]
#        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies Public UI
        run: npm install
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        env:
            DB_CONNECTION: sqlite
            DB_DATABASE: database/database.sqlite
            APP_URL: ${{ vars.APP_URL }}
        run: vendor/bin/phpunit
